### ISSUE TITLE
Changes in the security group ids list in SecurityGroupPolicy are not propagate

### ISSUE THREAD

**Issue by renanqts** [aws/amazon-vpc-resource-controller-k8s#11]
**Is your feature request related to a problem? Please describe.**
If I add/remove a security group from my manifest (SecurityGroupPolicy) and apply it, it doesn't propagate the change in the branch ENI.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Right now a pod recreation is required in order to create a new ENI with security groups specified in the manifest.

**Additional context**
EKS version 1.18
CNI plugin 1.7.5

I also couldn't see any events from the controller into the resource when I do a "kubectl describe sgp ..."

**Comment by swade1987** [comment]
This is going to come across as pretty direct .... 

> I feel the current implementation of this functionality is broken.

Having to restart the pod to pick up a new SG being added just seems broken, you do not have to do this with ec2 instances.

Having to remember to do this for pods has caused major problems for us in the last few months.

Additionally, we have found that making changes to the SG itself (like changing the ports) is not reflected in the pods behaviour again until the pod is restart.

**Comment by adriantaut** [comment]
Hello, guys. Are there any news on this particular issue? 

Unfortunately it's not only about the new SGs or Rules not being applied, but we are suffering a lot since everything seems to be updated accordingly, but in fact the Pods were not updated. This lack of transparency makes the problem very difficult to diagnose by people deploying in EKS.

A bit offtopic: we are applying the `kubernetes.io/cluster/${this.cluster.clusterName}: owned` Tag to the SecurityGroup for Pod in order to accomplish the ALB creation that seems to check for this tag on the SGs attached to the Pod ENI. If you apply the Tag, it exists a lag of 1-2 minutes, but in the end the EKS manages to see the tag update in the SG. Maybe some similar update mechanism can be applied for this issue also.

**Comment by dewjam** [comment]
With #103, the pod controller could watch for updates to SecurityGroupPolicy resources and then reconcile applicable pods.  More work would have to be done to ensure pod reconciliation updates Security Groups accordingly, though.

**Comment by sushrk** [comment]
>Additionally, we have found that making changes to the SG itself (like changing the ports) is not reflected in the pods behaviour again until the pod is restart.

>Unfortunately it's not only about the new SGs or Rules not being applied

@swade1987/ @adriantaut Regarding the changes to SG rules specifically, I was not able to reproduce this behavior.
Security group rule updates should be reflected on a running pod almost automatically. Could you please provide more details on this? 

As of now, we are not planning to have the changes to security group policies be propagated to existing pods. Please create an issue at [containers-roadmap](https://github.com/aws/containers-roadmap) if this should be supported by AWS EKS so we can evaluate it further. Thanks. 

I'm closing this issue.
